import Navigation from "@/components/Navigation";

export const metadata = {
  title: "Next 15",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <Navigation />
      <section className="">{children}</section>
    </div>
  );
}
