import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Work_Sans } from "next/font/google";

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/psylocke.jpg",
  },
  metaDatabase: new URL("https://nextjs.org/"),
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "https://nextjs.org/",
    siteName: "Next.js",
    images: [
      {
        url: "/og-image.png", //replaces with above metaDatabase url
        width: 1200,
        height: 630,
        alt: "Next.js Logo",
      },
    ],
    type: "website",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased  ${workSans.variable} `}
      >
        {children}
      </body>
    </html>
  );
}
